Fixed stealMessage in Doppelganger and Necromancer
Kyubendo/werewolf-telegram-bot pull request #119
Opened 2021-12-01 12:00 UTC by SuperMetal-chan

2021-12-01 19:26 UTC, Kyubendo requested changes

2021-12-01 19:26 UTC, Kyubendo commented on src/Roles/Abstract/RoleBase.ts
> +    getAlliesMessage?: (notify?: boolean) => Promise<string>
Почему notify опициональный? ЛУчше тогда значение по умолчанию просто.

2021-12-01 19:26 UTC, Kyubendo commented on src/Roles/Others/Undertaker.ts
> +            `но когда ты видишь такой прекрасный труп ты не можешь задуматься, ` +
А тут не "не можешь не задуматься"?

2021-12-01 19:26 UTC, Kyubendo commented on src/Roles/Villagers/Mason.ts
>          return (allies?.length > 1
Наверное, лучше тут сразу отправлять эти сообщения, а функция sendAlliesMessage. 
Так не нужно будет лишних проверок и отправок в каждой роли делать. Просто ` .role.sendAlliesMessage.?()`

2021-12-01 19:26 UTC, Kyubendo commented on src/Roles/Villagers/Mason.ts
> +    getAlliesMessage = async (notify?: boolean): Promise<string> => {
Надо же ещё и вора тут описать.

2021-12-02 07:59 UTC, SuperMetal-chan commented on src/Roles/Abstract/RoleBase.ts
> +    getAlliesMessage?: (notify?: boolean) => Promise<string>
> 

![image](https://user-images.githubusercontent.com/81335543/144381140-f14e9215-d363-4cca-ac62-78bee549f681.png)

2021-12-02 08:54 UTC, Kyubendo commented on src/Roles/Abstract/RoleBase.ts
> +    getAlliesMessage?: (notify?: boolean) => Promise<string>
Так параметр по умолчанию не объявлении, а в определении функции. А тут надо опциональность убрать.

2021-12-14 13:11 UTC, Kyubendo approved these changes

2021-12-14 13:11 UTC, merged